// <auto-generated />
namespace Hola.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class mnu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mnu));
        
        string IMigrationMetadata.Id
        {
            get { return "202103092022375_mnu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
